#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsondiff
Version  : 1.2.0
Release  : 7
URL      : https://files.pythonhosted.org/packages/64/5c/2b4b0ae4d42cb1b0b1a89ab1c4d9fe02c72461e33a5d02009aa700574943/jsondiff-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/64/5c/2b4b0ae4d42cb1b0b1a89ab1c4d9fe02c72461e33a5d02009aa700574943/jsondiff-1.2.0.tar.gz
Summary  : Diff JSON and JSON-like structures in Python
Group    : Development/Tools
License  : MIT
Requires: jsondiff-bin = %{version}-%{release}
Requires: jsondiff-license = %{version}-%{release}
Requires: jsondiff-python = %{version}-%{release}
Requires: jsondiff-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
jsondiff
========
Diff JSON and JSON-like structures in Python.
Installation
------------

%package bin
Summary: bin components for the jsondiff package.
Group: Binaries
Requires: jsondiff-license = %{version}-%{release}

%description bin
bin components for the jsondiff package.


%package license
Summary: license components for the jsondiff package.
Group: Default

%description license
license components for the jsondiff package.


%package python
Summary: python components for the jsondiff package.
Group: Default
Requires: jsondiff-python3 = %{version}-%{release}

%description python
python components for the jsondiff package.


%package python3
Summary: python3 components for the jsondiff package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jsondiff package.


%prep
%setup -q -n jsondiff-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1561312660
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsondiff
cp LICENSE %{buildroot}/usr/share/package-licenses/jsondiff/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jdiff
/usr/bin/jsondiff

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsondiff/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
